
import { Inter } from 'next/font/google'
import Provider from '../components/Provider'
import { getServerSession } from "next-auth"
import { redirect } from "next/navigation";
import { authOptions } from "../api/auth/[...nextauth]/route"
import { useSession } from 'next-auth/react';
import HeaderLogado from '../components/HeaderLogado';
import 'bootstrap/dist/css/bootstrap.css';
import AuthChecker from '../components/AuthChecker';
import { styled } from 'styled-components';
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default async function RootLayout({children,}: {children: React.ReactNode}) {
  

  return (
    <html lang="en">
      <body className='bg-gray-200'>
        <Provider>
          <AuthChecker>
            <div className='container-fluid'>
            <HeaderLogado />
            
              {children}
              </div>
          </AuthChecker>
        </Provider>
      </body>
    </html>
  )
}
