
import { Inter } from 'next/font/google'
import Provider from '../components/Provider'
import { getServerSession } from "next-auth"
import { redirect } from "next/navigation";
import { authOptions } from "../api/auth/[...nextauth]/route"
import { useSession } from 'next-auth/react';
import HeaderLogado from '../components/HeaderLogado';
import AuthChecker from '../components/AuthChecker';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({children,}: {children: React.ReactNode}) {
  

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <AuthChecker>
            <HeaderLogado />
            {children}
          </AuthChecker>
        </Provider>
      </body>
    </html>
  )
}
